name: Glytoucan Developer Site
description: Site for the development of Glytoucan and Glycan-related datastores
url: http://code.glytoucan.org
exclude: [deprecated]
safe: true
highlighter: rouge
markdown: kramdown
paginate: 2
paginate_path: "/blog/page:num/"
permalink: pretty
#permalink: :categories/:title
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data', 'superscript']
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at
