name: Glytoucan Developer Site
description: Site for the development of Glytoucan and Glycan-related datastores
url: http://nobu.glytoucan.org/
permalink: :categories/:title
exclude: [deprecated]
safe: true
highlighter: pygments
markdown: redcarpet
paginate: 2
paginate_path: "/news/page:num/"
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data', 'superscript']
#gems: [jekyll-paginate]
